volumes: 
  forgejo:
  forgejo_postgres:
  docker_certs:

networks:
  proxy:
    external: true
  forgejo:


services:
# git setup ----------------------------------------------------------
  git:
    image: codeberg.org/forgejo/forgejo:15
    command: >-
      bash -c '
      /usr/bin/s6-svscan /etc/s6 &
      sleep 10 ;
      su -c "forgejo forgejo-cli actions register --secret ${SHARED_SECRET}" git ;
      su -c "forgejo admin user create --admin --username root --password ${ROOT_PASSWORD} --email root@nuv.direct" git ;
      sleep infinity
      '
    restart: unless-stopped      
    container_name: git
    environment: 
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo
      - FORGEJO__DEFAULT__APP_NAME="Butter dog"
      - FORGEJO__DEFAULT__APP_SLOGAN="the dog with the butter"
      - FORGEJO__server__ROOT_URL=https://git.ollie.earth
      - FORGEJO__server__OFFLINE_MODE=false
      - FORGEJO__mirror__ENABLED=true
    networks:
      - proxy
      - forgejo
    ports:
      - "222:22"
    volumes:
      - forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on: 
      - db
    deploy:
      resources:
        limits:
          memory: 2G

  anubis:
    image: ghcr.io/techarohq/anubis:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      BIND: ":3000"
      DIFFICULTY: "5"
      TARGET: http://git:3000
      METRICS_BIND: ":9091"
    networks:
      - proxy
      - forgejo
    labels:
      caddy_0: git.ollie.earth
      caddy_0.reverse_proxy: "{{upstreams 3000}}"

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=forgejo
      - POSTGRES_DB=forgejo
    networks: 
      - forgejo
    volumes:
      - forgejo_postgres:/var/lib/postgresql/data

