volumes:
  tangled_keys:
  tangled_server:
  tangled_server1:

networks:
  proxy:
    external: true

services: 
  knot:
    image: atcr.io/tangled.org/knot:v1.14.0-alpha
    restart: unless-stopped
    container_name: tangled_knot
    environment: 
      KNOT_SERVER_HOSTNAME: knot.ollie.earth
      KNOT_SERVER_OWNER: ${KNOT_SERVER_OWNER}
      KNOT_SERVER_DB_PATH: /app/knotservr.db
      KNOT_REPO_SCAN_PATH: /home/git/repositories
      KNOT_SERVER_INTERNAL_LISTEN_ADDR: localhost:5444
    volumes:
      - tangled_keys:/etc/ssh/keys
      - ./data/repos:/home/git/repositories
      - tangled_server:/app
    ports: 
      - "2222:22"
    networks:
      - proxy
    labels:
      caddy_0: knot.ollie.earth
      caddy_0.reverse_proxy: "{{upstreams 5555}}"
      caddy_1: knot.nuv.sh
      caddy_1.reverse_proxy: "{{upstreams 5555}}"
